export const items = [
  {
    _id: '6771f251f763dedbd48654da',
    name: '우산',
    tags: ['우산', '공학관', '검정색'],
    status: true,
    createdAt: '2024.12.30',
    image: {
      data: 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/wcAAwAB/GOvteMAAAAASUVORK5CYII=',
      ext: '.png',
      contentType: 'image/png',
    },
    __v: 0,
  },
  {
    _id: '6771f251f763dedbd48654da',
    name: '가방',
    tags: ['가방', 'ICT관', '백팩', '검정색'],
    status: true,
    createdAt: '2024.12.30',
    image: {
      data: 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/wcAAwAB/GOvteMAAAAASUVORK5CYII=',
      ext: '.png',
      contentType: 'image/png',
    },
    __v: 0,
  },
  {
    _id: '6771f251f763dedbd48654da',
    name: '구찌 지갑',
    tags: ['지갑', '인문관', '검정색'],
    status: true,
    createdAt: '2024.12.30',
    image: {
      data: 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/wcAAwAB/GOvteMAAAAASUVORK5CYII=',
      ext: '.png',
      contentType: 'image/png',
    },
    __v: 0,
  },
  {
    _id: '6771f251f763dedbd48654da',
    name: '파우치',
    tags: ['흰색', '공학관'],
    status: true,
    createdAt: '2024.12.30',
    image: {
      data: 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/wcAAwAB/GOvteMAAAAASUVORK5CYII=',
      ext: '.png',
      contentType: 'image/png',
    },
    __v: 0,
  },
  {
    _id: '6771f251f763dedbd48654da',
    name: '컵라면',
    tags: ['진라면', '상경관', '안오면제가먹을게요'],
    status: false,
    createdAt: '2024.12.30',
    image: {
      data: 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/wcAAwAB/GOvteMAAAAASUVORK5CYII=',
      ext: '.png',
      contentType: 'image/png',
    },
    __v: 0,
  },
  {
    _id: '6771f251f763dedbd48654da',
    name: '목도리',
    tags: ['줄무늬목도리', '2공학관'],
    status: false,
    createdAt: '2024.12.30',
    image: {
      data: 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/wcAAwAB/GOvteMAAAAASUVORK5CYII=',
      ext: '.png',
      contentType: 'image/png',
    },
    __v: 0,
  },
  {
    _id: '6771f251f763dedbd48654da',
    name: '스노우메이커',
    tags: ['오리모양', '곰상앞', '노랑색'],
    status: false,
    createdAt: '2024.12.30',
    image: {
      data: 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/wcAAwAB/GOvteMAAAAASUVORK5CYII=',
      ext: '.png',
      contentType: 'image/png',
    },
    __v: 0,
  },
];
